<a href="https://colab.research.google.com/github/substobeme/Path-prediction-using-LSTM/blob/main/Lstm_pathprediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
paths = [
    "/content/drive/MyDrive/Floor 4/Floor 4/train_4_1.csv",
    "/content/drive/MyDrive/Floor 4/Floor 4/train_4_10.csv",
    "/content/drive/MyDrive/Floor 4/Floor 4/train_4_13.csv",
    "/content/drive/MyDrive/Floor 4/Floor 4/train_4_15.csv",
    "/content/drive/MyDrive/Floor 4/Floor 4/train_4_17.csv",
    "/content/drive/MyDrive/Floor 4/Floor 4/train_4_18.csv",
    "/content/drive/MyDrive/Floor 4/Floor 4/train_4_25.csv",
    "/content/drive/MyDrive/Floor 4/Floor 4/train_4_11.csv",
    "/content/drive/MyDrive/Floor 4/Floor 4/train_4_12.csv",
    "/content/drive/MyDrive/Floor 4/Floor 4/train_4_14.csv",
    "/content/drive/MyDrive/Floor 4/Floor 4/train_4_16.csv",
    "/content/drive/MyDrive/Floor 4/Floor 4/train_4_19.csv",
    "/content/drive/MyDrive/Floor 4/Floor 4/train_4_2.csv",
    "/content/drive/MyDrive/Floor 4/Floor 4/train_4_20.csv",
    "/content/drive/MyDrive/Floor 4/Floor 4/train_4_21.csv",
    "/content/drive/MyDrive/Floor 4/Floor 4/train_4_22.csv",
    "/content/drive/MyDrive/Floor 4/Floor 4/train_4_23.csv",
    "/content/drive/MyDrive/Floor 4/Floor 4/train_4_24.csv",
    "/content/drive/MyDrive/Floor 4/Floor 4/train_4_26.csv",
    "/content/drive/MyDrive/Floor 4/Floor 4/train_4_27.csv",
    "/content/drive/MyDrive/Floor 4/Floor 4/train_4_28.csv",
    "/content/drive/MyDrive/Floor 4/Floor 4/train_4_29.csv",
    "/content/drive/MyDrive/Floor 4/Floor 4/train_4_3.csv",
    "/content/drive/MyDrive/Floor 4/Floor 4/train_4_30.csv",
    "/content/drive/MyDrive/Floor 4/Floor 4/train_4_32.csv",
    "/content/drive/MyDrive/Floor 4/Floor 4/train_4_31.csv",
    "/content/drive/MyDrive/Floor 4/Floor 4/train_4_33.csv",
    "/content/drive/MyDrive/Floor 4/Floor 4/train_4_34.csv",
    "/content/drive/MyDrive/Floor 4/Floor 4/train_4_35.csv",
    "/content/drive/MyDrive/Floor 4/Floor 4/train_4_36.csv",
    "/content/drive/MyDrive/Floor 4/Floor 4/train_4_37.csv",
    "/content/drive/MyDrive/Floor 4/Floor 4/train_4_38.csv",
    "/content/drive/MyDrive/Floor 4/Floor 4/train_4_39.csv",
    "/content/drive/MyDrive/Floor 4/Floor 4/train_4_4.csv",
    "/content/drive/MyDrive/Floor 4/Floor 4/train_4_40.csv"

]

In [3]:
import pandas as pd

In [4]:
from sklearn.preprocessing import MinMaxScaler

In [6]:
df2=[]
scaler = MinMaxScaler()
y=[]
for path in paths:
  r=pd.read_csv(path)
  r_normalized = pd.DataFrame(scaler.fit_transform(r), columns=r.columns)
  df2.append(r_normalized.loc[:148,["x","y","z"]].values.tolist())
  y.append(list(r_normalized.loc[149,["x","y","z"]]))

df2

[[[0.12492927550023075, 0.0, 0.4916887193717394],
  [0.12516172765550077, 0.003459268085353403, 0.4856166364892811],
  [0.1254505275056224, 0.03680981906056448, 0.27826049690905075],
  [0.12536994704489235, 0.08990794350607317, 0.44749938395277367],
  [0.12455592153690975, 0.12130677046551766, 0.5699776080225423],
  [0.12499009192556423, 0.15463998108246946, 0.3224069768687663],
  [0.12417944076508836, 0.19055559788381468, 0.1598963969272642],
  [0.12443576089191169, 0.21883545461937537, 0.43770423304798767],
  [0.12421043525434891, 0.25109460344574785, 0.46132294802704177],
  [0.12341342479595621, 0.2876231618953471, 0.05141583723496668],
  [0.12420535419053574, 0.3184497837097098, 0.29241083386009903],
  [0.12455099681352155, 0.35408435331988364, 0.3462346122116635],
  [0.12461284247998647, 0.3901777754870719, 0.3225730417733592],
  [0.12392545271627159, 0.4287776263920039, 0.2812577005903343],
  [0.1250977583649293, 0.4677468536053325, 0.45946141401587814],
  [0.12476304654332623, 0

In [7]:
len(df2[0])

149

In [20]:
len(df2)

35

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train, X_test, y_train, y_test = train_test_split( df2, y, test_size=0.2, random_state=42)

In [21]:
len(X_test)

7

In [10]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense,BatchNormalization,Dropout,Bidirectional
from tensorflow.keras.losses import MeanAbsoluteError,MeanSquaredError,Huber

In [11]:
from keras.regularizers import l2

In [12]:
model = Sequential([
    LSTM(units=64, input_shape=(149,3), return_sequences=True, kernel_regularizer=l2(0.01)),

    LSTM(units=32, return_sequences=True, kernel_regularizer=l2(0.01)),

    LSTM(units=16,return_sequences=True, kernel_regularizer=l2(0.01)),
    LSTM(units=8, kernel_regularizer=l2(0.01)),

    Dense(units=3)
])

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 149, 64)           17408     
                                                                 
 lstm_1 (LSTM)               (None, 149, 32)           12416     
                                                                 
 lstm_2 (LSTM)               (None, 149, 16)           3136      
                                                                 
 lstm_3 (LSTM)               (None, 8)                 800       
                                                                 
 dense (Dense)               (None, 3)                 27        
                                                                 
Total params: 33787 (131.98 KB)
Trainable params: 33787 (131.98 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [14]:
model.compile(optimizer='adam', loss='mse')

In [15]:
model.fit(X_train, y_train,validation_data=(X_test,y_test),epochs=28, batch_size=32, verbose=1)

Epoch 1/28
1/1 [==============================] - 9s 9s/step - loss: 1.7857 - val_loss: 1.7396
Epoch 2/28
1/1 [==============================] - 0s 313ms/step - loss: 1.7180 - val_loss: 1.6763
Epoch 3/28
1/1 [==============================] - 1s 521ms/step - loss: 1.6618 - val_loss: 1.6228
Epoch 4/28
1/1 [==============================] - 0s 492ms/step - loss: 1.6145 - val_loss: 1.5779
Epoch 5/28
1/1 [==============================] - 0s 415ms/step - loss: 1.5748 - val_loss: 1.5402
Epoch 6/28
1/1 [==============================] - 0s 395ms/step - loss: 1.5413 - val_loss: 1.5087
Epoch 7/28
1/1 [==============================] - 0s 407ms/step - loss: 1.5128 - val_loss: 1.4821
Epoch 8/28
1/1 [==============================] - 0s 417ms/step - loss: 1.4881 - val_loss: 1.4593
Epoch 9/28
1/1 [==============================] - 0s 242ms/step - loss: 1.4662 - val_loss: 1.4393
Epoch 10/28
1/1 [==============================] - 0s 261ms/step - loss: 1.4464 - val_loss: 1.4214
Epoch 11/28
1/1 [=====

In [16]:
pred=model.predict(X_test)

1/1 [==============================] - 2s 2s/step


In [17]:
pred

array([[0.34872636, 0.5822753 , 0.36524433],
       [0.23888946, 0.46401843, 0.3334055 ],
       [0.33752254, 0.58308256, 0.37702724],
       [0.3557873 , 0.59076774, 0.36830214],
       [0.3294758 , 0.5740045 , 0.3742066 ],
       [0.23879534, 0.48148564, 0.34861195],
       [0.26763022, 0.5294658 , 0.3758577 ]], dtype=float32)

In [18]:
mae = MeanAbsoluteError()
mse=MeanSquaredError()


loss1 = mae(y_test,pred)

loss3=mse(y_test,pred)

print("Loss%:", loss1.numpy()*100)

print("Loss%",loss3.numpy()*100)

Loss%: 14.34144526720047
Loss% 3.96946482360363


In [22]:
new = X_test
for i in range(5):
  for j in range(len(X_test)):
    pred1=model.predict(new)
    print(pred1)
    new[j].append(pred1[j])
    new[j].pop(0)



1/1 [==============================] - 0s 111ms/step
[[0.34872636 0.5822753  0.36524433]
 [0.23888946 0.46401843 0.3334055 ]
 [0.33752254 0.58308256 0.37702724]
 [0.3557873  0.59076774 0.36830214]
 [0.3294758  0.5740045  0.3742066 ]
 [0.23879534 0.48148564 0.34861195]
 [0.26763022 0.5294658  0.3758577 ]]
1/1 [==============================] - 0s 116ms/step
[[0.34656012 0.580094   0.36501557]
 [0.23888946 0.46401843 0.3334055 ]
 [0.33752254 0.58308256 0.37702724]
 [0.3557873  0.59076774 0.36830214]
 [0.3294758  0.5740045  0.3742066 ]
 [0.23879534 0.48148564 0.34861195]
 [0.26763022 0.5294658  0.3758577 ]]
1/1 [==============================] - 0s 124ms/step
[[0.34656012 0.580094   0.36501557]
 [0.23963821 0.46562788 0.3350531 ]
 [0.33752254 0.58308256 0.37702724]
 [0.3557873  0.59076774 0.36830214]
 [0.3294758  0.5740045  0.3742066 ]
 [0.23879534 0.48148564 0.34861195]
 [0.26763022 0.5294658  0.3758577 ]]
1/1 [==============================] - 0s 65ms/step
[[0.34656012 0.580094   0.3650

In [25]:
new[1]

[[0.165067331171532, 0.7715817920546911, 0.352511126846045],
 [0.14647181313992785, 0.7787433141226429, 0.39534948411895643],
 [0.12594727138670003, 0.7781707483440211, 0.2717226380740443],
 [0.10817655378303255, 0.778699516772282, 0.23483461460651434],
 [0.08961945399272724, 0.7815665821523083, 0.4229744082540967],
 [0.07139110055408254, 0.7843020726113131, 0.4932530851709487],
 [0.05708504708099088, 0.7852026156253096, 0.37983764920089014],
 [0.04459624818322276, 0.7847133775821692, 0.38980123406837963],
 [0.035796459029912214, 0.7722734061635214, 0.4068354238316809],
 [0.04300386462134509, 0.7657630534695852, 0.012879324296985573],
 [0.08464412515443064, 0.777329973321714, 0.1800703014363747],
 [0.10809061891773918, 0.7747819550283807, 0.4787199069391064],
 [0.12384022691520218, 0.7693855545671096, 0.5958501921909769],
 [0.13385349684229098, 0.7394989680649349, 0.8455290309528629],
 [0.13573748997688206, 0.6771646101316527, 0.35308264212017004],
 [0.13480422657551216, 0.621132407466